### ISSUE TITLE
Legendas omissas no começo e no final da primeira abertura (episódios 1-2).

### ISSUE THREAD

**Issue by Mazzocca** [Monaco-a-Knox/language_pt#1]
Desde a instalação do script e da tradução mais recentes em português (o port já havia sido previamente instalado e, nas primeiras tentativas de solucionar essa falta das legendas, reinstalado em uma instalação limpa mais de uma vez), eu acabei notando que faltavam legendas da música da primeira abertura no começo e no final dela, como se pode constatar por essas screenshots em anexo. É possível que seja um oversight da tradução ou o problema não possui relação nenhuma com ela e é inerente ao port?
![onscripter-ru_GV1K2rAjd2](https://user-images.githubusercontent.com/111713116/185816973-8fde0a85-88e3-4c3a-a77d-11debf97f423.png)
![onscripter-ru_UJrWR7yrmy](https://user-images.githubusercontent.com/111713116/185817019-9f48992a-a5a4-4b96-9b2b-5981a23a98c3.png)
![onscripter-ru_u4u6zzT27b](https://user-images.githubusercontent.com/111713116/185817021-8a475825-4bbb-4bdc-ba1f-99bd9205479c.png)
![onscripter-ru_gOP0hfnGvp](https://user-images.githubusercontent.com/111713116/185817054-ae263e99-fc30-469d-995a-5c49b30f5092.png)

A versão do script usada é a r4011, também constando na borda da janela do port em todas as capturas de tela.

Grato desde já pela atenção.

**Comment by Monaco-a-Knox** [comment]
Se você fala dos supostos versos em alemão, eles foram removidos faz mais de um ano porque não há 100% de certeza que é essa mesmo a letra, embora pareça muito. Se os quiser, basta editar as legendas e desmarcar as linhas que ficaram marcadas como comentário.

**Comment by Mazzocca** [comment]
O arquivo em questão seria ou o pt.cfg ou pt.file? Ou algum outro?

**Comment by Monaco-a-Knox** [comment]
> O arquivo em questão seria ou o pt.cfg ou pt.file? Ou algum outro?

São os .ass que ficam na pasta sub.
https://github.com/Monaco-a-Knox/language_pt/tree/master/language_pt/video/sub

Vai precisar de um programa simples de edição como o notepad++ ou o aegisub, para abrir e visualizar melhor.

**Comment by Mazzocca** [comment]
Acabei editando ambos pt.ass e rom_pt.ass, substituindo a marcação de comentário como foi instruído, mas não houve alteração nenhuma nas legendas. Elas ainda continuam omissas.

**Comment by Mazzocca** [comment]
Mesmo após repetidas tentativas de trocar as marcações de comentário pelas de diálogo, não há alteração nenhuma nas legendas. Eu estou fazendo algo de errado (possível que seja meio óbvio, já que eu sou completamente leigo)?

**Comment by Mazzocca** [comment]
> > O arquivo em questão seria ou o pt.cfg ou pt.file? Ou algum outro?
> 
> São os .ass que ficam na pasta sub. https://github.com/Monaco-a-Knox/language_pt/tree/master/language_pt/video/sub
> 
> Vai precisar de um programa simples de edição como o notepad++ ou o aegisub, para abrir e visualizar melhor.

Mais ou menos dessa forma? Mesmo editando os arquivos desse modo, as legendas ainda não aparecem.

Acréscimo:  O arquivo both_pt_.ass também foi editado, mas ele não consta nas screenshots. Mesmo com os três arquivos tendo as marcações substituídas como indicado, nada muda.
![notepad++_mB3xMtPSR3](https://user-images.githubusercontent.com/111713116/187086764-9a4c96e7-18fb-4151-a11b-6683e065cf0c.png)

![notepad++_GAwqkitQAp](https://user-images.githubusercontent.com/111713116/187086825-15f2b77b-b14c-47a1-8224-521f4c458c7d.png)

**Comment by Monaco-a-Knox** [comment]
Se você quer tradução+romaji, é o arquivo "both".
Os "comment" precisam virar "dialogue". Supostamente deveria funcionar... Se não estiver funcionando, tente fazer isso com o Aegisub.

**Comment by Mazzocca** [comment]
> Se você quer tradução+romaji, é o arquivo "both". Os "comment" precisam virar "dialogue". Supostamente deveria funcionar... Se não estiver funcionando, tente fazer isso com o Aegisub.
![image](https://user-images.githubusercontent.com/111713116/187456212-4b40003e-31cc-4baf-81b1-ee05e54af940.png)

O arquivo both_pt.ass em questão. Pretendo tentar com o Aegisub, então.

**Comment by Mazzocca** [comment]
> > Se você quer tradução+romaji, é o arquivo "both". Os "comment" precisam virar "dialogue". Supostamente deveria funcionar... Se não estiver funcionando, tente fazer isso com o Aegisub.
> > ![image](https://user-images.githubusercontent.com/111713116/187456212-4b40003e-31cc-4baf-81b1-ee05e54af940.png)
> 
> O arquivo both_pt.ass em questão. Pretendo tentar com o Aegisub, então.

Mesmo realizando a edição pelo Aegisub, não consta nenhuma alteração na legenda, como indicado por essa screenshot. A configuração de legendas para as canções também consta como "ambos".
![image](https://user-images.githubusercontent.com/111713116/187479711-b2b949ca-a287-4066-b4b5-89f5ef09bcf6.png)
![image](https://user-images.githubusercontent.com/111713116/187480349-63a70ef9-847e-4edb-89bd-ecc0e746402b.png)
![image](https://user-images.githubusercontent.com/111713116/187479095-2db586e7-cf83-4d22-8e5d-995500c2cc6d.png)

**Comment by Monaco-a-Knox** [comment]
Estou sem meu computador, então não tenho como testar para ajudar.
Você precisa mesmo disso?

**Comment by Mazzocca** [comment]
Eu posso esperar até tu ter acesso a um. É mais preferência estética minha (ter as legendas completas) do que qualquer outra razão, na verdade.

**Comment by Mazzocca** [comment]
> Estou sem meu computador, então não tenho como testar para ajudar. Você precisa mesmo disso?

Alguma novidade sobre o teste?
(Eu encerrei e reabri a issue por acidente. Pode ignorar isso).

**Comment by Monaco-a-Knox** [comment]
Testei e funcionou normalmente, então não sei dizer qual o problema.
A solução é baixar um release anterior que ainda tenha a letra. Experimente pegar só as legendas desse.

https://github.com/Monaco-a-Knox/language_pt/releases/tag/01.06.2021

**Comment by Mazzocca** [comment]
> 

Certo. Espero que essa seja a solução.

Atualização: Não houve alteração nas legendas, que continuam sem aparecer. Pode por acaso ter a ver com o arquivo de savegame? Se for necessário reiniciar os episódios que eu já joguei do zero, por mim tudo bem.

E o estranho é que as legendas aparecem normalmente no Aegisub, mas não na visual novel.

https://user-images.githubusercontent.com/111713116/196012427-5f1c01d5-455e-4713-b18e-9d8abdf7a9d6.mp4

**Comment by Monaco-a-Knox** [comment]
Honestamente, eu não sei dizer o motivo.
Talvez indo nas configurações e reiniciando. Não posso ajudá-lo além disso.

**Comment by Mazzocca** [comment]
> Honestamente, eu não sei dizer o motivo. Talvez indo nas configurações e reiniciando. Não posso ajudá-lo além disso.

É, pelo jeito eu vou ser obrigado a desistir da mesma forma. Mesmo com a função de restauração do jogo, as legendas insistem em não aparecer. Talvez uma reinstalação limpa corrija isso, mas eu não me encontro com muito tempo disponível pra tentar isso. Pode se sentir à vontade pra fechar esse tópico, se quiser.

**Atualização**: Uma reinstalação limpa acabou resolvendo. Quem diria que a solução mais simples seria a mais eficaz?

Enfim, agradeço imensamente pela ajuda, Knox. E fico no aguardo de atualizações posteriores da tradução.
![image](https://user-images.githubusercontent.com/111713116/196323947-09d60a52-aa86-4219-863f-813bb6a10164.png)
